Repository bredbrains/tthk-wish-list-client, pull requests merged in 2021-05, with the labels that each got.

#8 #135 Add validation to fields
  pages/wishes/add.vue
  store/modules/wishes.js
Labels: bug, invalid

#11 Add delete confirmation dialog and move forms to v-form with Enter button submit
  pages/login.vue
  pages/register.vue
  pages/wishes/add.vue
  pages/wishes/index.vue
Labels: new feature

#13 #113 - Editing Wishes
  pages/wishes/add.vue
  pages/wishes/index.vue
  store/index.js
  store/modules/wishes.js
Labels: new feature

#14 #156 "Add wish" button replacement
  layouts/default.vue
  pages/index.vue
  pages/wishes/add.vue
  pages/wishes/index.vue
  yarn.lock
Labels: refactoring
